stages:
  - test
  - sonarqube
  - test ansible playbook
  - build docker
  - deploy
  - telegram

include:
  - .gitlab/ci/tests/test.yml # везде # на ранере гитлаба
  #- .gitlab/ci/tests/sonarqube.yml # везде # на ранере гитлаба
  #- .gitlab/ci/tests/test-ansible-playbook.yml # везде # на ранере гитлаба
  - .gitlab/ci/image.yml # только в мастер ветке # на ранере гитлаба
  - .gitlab/cd/deploy.yml # только в мастер ветке # на собственом ранере
  - .gitlab/cd/telegram.yml # только в мастер ветке # на ранере гитлаба