stages:
  - test
  - build docker
  - deploy
  - telegram

variables:
  TELEGRAM_BOT_TOKEN: "1"
  TELEGRAM_GROUP_ID: "2" 

include:
  - .gitlab/ci/tests/test.yml # везде
  #- .gitlab/ci/image.yml # только в мастер ветке
  #- .gitlab/cd/deploy.yml # только в мастер ветке
  - .gitlab/cd/telegram.yml # везде