stages:
  - test
  - build docker
  - deploy
  - telegram

include:
  - .gitlab/ci/tests/test.yml # везде
  #- .gitlab/ci/image.yml # только в мастер ветке
  #- .gitlab/cd/deploy.yml # только в мастер ветке
  - .gitlab/cd/telegram.yml # везде