stages:
  - test
  - build docker
  - deploy
  
test project job:
  image: python:latest
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test --noinput # запуск тестов tests.py

build image job:
  stage: build docker
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY}/georg-get/ping-lotus .
    - docker push ${CI_REGISTRY}/georg-get/ping-lotus
  only:
    - master
    # - merge_requests

#deploy job:
  #stage: deploy
  #before_script:
    #- docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  #script:
    #- cp ./docker-compose.yml /var/www
    #- cd /var/www
    #- docker-compose pull ${CI_REGISTRY_IMAGE}
    #- docker-compose stop ${CI_REGISTRY_IMAGE} || true #&& docker-compose rm ${CI_REGISTRY_IMAGE} || true
    #- docker-compose up -d --force-recreate
  #only:
    #- master
  #tags:
    #- test # prom