stages:
  - test
  - build docker
  - deploy


include:
  - .gitlab/ci/tests/test.yml
  - .gitlab/ci/image.yml
  
# запуск тестов tests.py
    # - merge_requests

#deploy job:
  #stage: deploy
  #before_script:
    #- docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  #script:
    #- cp ./docker-compose.yml /var/www
    #- cd /var/www
    #- docker-compose pull ${CI_REGISTRY_IMAGE}
    #- docker-compose stop ${CI_REGISTRY_IMAGE} || true #&& docker-compose rm ${CI_REGISTRY_IMAGE} || true
    #- docker-compose up -d --force-recreate
  #only:
    #- master
  #tags:
    #- test # prom