version: '3.7'

services:
  django:                       # название 
    image: registry.gitlab.com/georg-get/ping-lotus:latest
    #volumes:
      #- .:/ping-lotus
    ports:
      - "0.0.0.0:8000:8000"      # порт наружу

      # main/* mysite/* manage.py requirements.txt ./ping-lotus/ 
