version: '3.7'
                    #Для тестирование локальных образов
services:

  django:                  
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000

  postgres:
    image: postgres:14.2-alpine
    depends_on:
      - django
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
    - /var/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db