version: '3.7'

services:
  django:                  
    image: registry.gitlab.com/georg-get/ping-lotus:latest
    container_name: Django
    restart: unless-stopped
    ports:
      - $DJANGO_PORT:$DJANGO_PORT   
    networks:
      - app 

  postgres:
    image: postgres:14.2-alpine
    container_name: PostgreSQL
    depends_on:
      - django
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
    - /var/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - app

  sonar:
    image: sonarqube:8.9.8-community
    container_name: SonarQube
    depends_on:
      - postgres
    restart: unless-stopped    
    ports:
      - $SONARQUBE_PORT:$SONARQUBE_PORT
    volumes:
      - /var/www/.sonarqube/conf:/opt/sonarqube/conf
      - /var/www/.sonarqube/data:/opt/sonarqube/data
      - /var/www/.sonarqube/extensions:/opt/sonarqube/extensions
      - /var/www/.sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - app


#volumes:


networks:
  app:
    driver: bridge