version: '3.7'

services:
  django:                   # название 
    image: registry.gitlab.com/georg-get/ping-lotus:latest
    restart: unless-stopped
    ports:
      - 8000:8000     # порт наружу

  postgres:
    image: postgres:14.2-alpine
    depends_on:
      - django
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
    - /var/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

  sonar:
    image: sonarqube:8.9.8-community
    depends_on:
      - postgres
    restart: unless-stopped    
    ports:
      - 9000:9000
    volumes:
      - /var/www/.sonarqube/conf:/opt/sonarqube/conf
      - /var/www/.sonarqube/data:/opt/sonarqube/data
      - /var/www/.sonarqube/extensions:/opt/sonarqube/extensions
      - /var/www/.sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins