services:
   django:
     build: ./project
     command: sh -c "gunicorn --bind 0.0.0.0:8000 app.wsgi"
     volumes:
       - ./project:/project
       - static_data:/project/static
     expose:
       - 8000
    # environment:
      # - DATABASE_URL=postgresql://django:django_QWErty!2)4@db:5432/django
      # - DEBUG=1

   db:
     image: mysql:5.7:13-alpine
     volumes:
     expose:
       -5432
     environment:
        MYSQL_DATABASE: 'db_django'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'

   nginx:
     image: nginx:1.19.8-alpine
     depends_on:
       - django
     ports:
       - "80:80"
     volumes:
       - static_data:/var/www/html/static
       - ./nginx-conf.d:/etc/nginx/conf.d
    volumes:
      mysql_data:
      static_data:
