version: '3.9'

services:
  django:
    build: ./project
    command: sh -c "gunicorn --bind 0.0.0.0:8000 app.wsgi"
    volumes:
      - ./project:/project
      - static_data:/project/static
    expose:
      - 8000
    #environment:
      #- DATABASE_URL=postgresql://"имя пользователя":"пароль":5432/"имя бд" # настройки бд
      #- DEBUG=1
  
  nginx:
    image: nginx:1.19.8-alpine
    depends_on: #запуск после Django
      - django
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d
      
  #db:                           # Postgresql
    #image: postgres:13-alpine
    #volumes:
      #- pg_data:/var/lib/postgresql/data
    #expose:
      #- 5432
    #environment:
      #- POSTGRES_USER="имя пользователя"
      #- POSTGRES_PASSWORD="пароль"
      #- POSTGRES_DB="имя бд"

  #db:                           # Mysql
    #image: mysql:5.7:13-alpine
    #volumes:
    #expose:
      #- 5432
    #environment:
       #MYSQL_DATABASE: 'db_django'
       #MYSQL_USER: 'root'
       #MYSQL_PASSWORD: 'password'
       #MYSQL_ROOT_PASSWORD: 'password'

volumes:
  #pg_data:     # Postgresql
  #mysql_data:  # Mysql
  static_data:  #1