--- 
name: test ansible

on: [push,pull_request]

jobs:
  test_ansible:
    runs-on: "ubuntu-latest"


    steps:
    - uses: actions/checkout@v3
    - name: install ansible and start test ansible-playbook
      run: |
        - pip install ansible -y
        - ansible-playbook ./infrastructure/ansible/ansible.yml
        - curl localhost
        - ansible-playbook ./infrastructure/ansible/rm_nginx.yml