--- 
name: test

on: [push,pull_request]

jobs:
  my_test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"] #запусти на этих версиях python


    steps:
    - uses: actions/checkout@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: install requirements and start test
      run: |
        pip install -r requirements.txt
        python3 manage.py test --noinput