--- 
name: test ansible

on: [push,pull_request]

jobs:
  test_ansible:
    runs-on: "ubuntu-latest"


    steps:
    - uses: actions/checkout@v3
    - uses: ./infrastructure/ansible/
      with: 
        playbook: ansible.yml

    - name: curl
      run: curl localhost

    - uses: ./infrastructure/ansible/
      with: 
        playbook: rm_nginx.yml