--- 
name: test ansible

on: [push,pull_request]

jobs:
  test_ansible:
    runs-on: "ubuntu-latest"


    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ansible
      with: 
        playbook: ansible.yml